# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35aa4235df2713dc0dbbe3b0db9acc1c20994f777752949bc8722ec65ae9497161a13e7f640e4203cc6efc890246e0fc04743de0b57438481fe0884cd9a50e10

test:
  secret_key_base: 12c3f702d8ca12a21f7c30b2c7e09d78595e969877f43b07e8b4af34a65f4c0eb89151294145d76a4ff80780ae80e88ff8317ac1fda12edc1bc95b964dab3521

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
